// position.idl
struct Position {
	string timestamp;
	string route;
	string vehicle;
	long stopNumber;
	long numStops;
	long timeBetweenStops;
	string trafficConditions;
	long fillInRatio;
};
// accident.idl
struct Accident {
	string timestamp;
	string route;
	string vehicle;
	long stopNumber;
};
